jaffle_shop:
  target: dev
  outputs:
    dev:
      account: sm15999.east-us-2.azure
      database: IDB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "dev_{{ env_var('SNOWFLAKE_USER') }}"
      threads: 8
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: IDB_WH
